#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

source "$HOME/.sq-addon/bin/variables.sh"
VENV=$(cat "$ADDON_VENV_FILE_LOCAL_PATH")

if [[ "$(uname)" == "MINGW"* ]] || [[ "$(uname)" == "CYGWIN"* ]] || [[ "$(uname)" == "MSYS"* ]]; then
    "$VENV"/Scripts/python.exe "$VENV"/Scripts/addon.exe "$@"
else
    "$VENV"/bin/python "$VENV"/bin/addon "$@"
fi
